"""add phone merchant

Revision ID: 02918756190b
Revises: a358812eeb34
Create Date: 2024-03-18 23:43:34.955499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02918756190b'
down_revision: Union[str, None] = 'a358812eeb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add phone column to Merchants
    op.add_column('Merchants', sa.Column('phone', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop phone column from Merchants
    op.drop_column('Merchants', 'phone')
    # ### end Alembic commands ###
