"""empty message

Revision ID: a358812eeb34
Revises: 4ffe4a7a6290
Create Date: 2023-11-25 11:42:02.636904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a358812eeb34'
down_revision: Union[str, None] = '4ffe4a7a6290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('role', sa.String(length=20), nullable = True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'role')
    # ### end Alembic commands ###
